#!/bin/bash

#case1: latency count value test (ssd:300ms, hdd:1000ms)
cat /sys/block/sdb/device/qnap_param_latency

#case2: latency count mechanism test
ioping /dev/sdb
echo 1 > /sys/block/sdb/device/qnap_param_latency
cat /dev/kmsg
hexdump -C /share/CACHEDEV1_DATA/.system_disk_data/*_201

#case4: check the latency time is issue with hal event.
tail -f /var/log/hal_daemon.log

#case3: scsi_times_out test
echo 1 > /sys/block/sdd/device/timeout
dd if=/dev/zero of=/root/file1 count=1
sg_raw -s 512 -i /root/file1 /dev/sdb 2a 00 00 00 00 00 00 00 02 00
hexdump -C /share/CACHEDEV1_DATA/.system_disk_data/*_201
"index 0x0a"
"count 0x0a"





